<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\FollowUp;
use DateTimeImmutable;use DateTimeZone;use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\Http\Request;use Dreamsmith\Campaign\Http\Response;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Presentation\ShellRenderer;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Security\Csrf;use Dreamsmith\Campaign\Support\Clock;
final class FollowUpController{
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $db,private readonly FollowUpService $service,private readonly ShellRenderer $shell,private readonly FlashBag $flash,private readonly Csrf $csrf,private readonly Router $router,private readonly Clock $clock){}
 public function schedule(Request $q,int $prospectId):Response{$u=$this->auth->user();if(!$u)return Response::redirect($this->router->url('login.form'),302);if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);try{$tz=new DateTimeZone((string)$this->db->pdo()->query('SELECT owner_timezone FROM application_settings WHERE id=1')->fetchColumn());$raw=(string)($q->body['due_at']??'');$due=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',$raw,$tz);if($due===false)throw new \InvalidArgumentException('Enter a valid due time.');$this->service->schedule($prospectId,(string)($q->body['action']??''),$due->setTimezone(new DateTimeZone('UTC')),(int)($q->body['prospect_version']??0),(int)$u['id'],$q->requestId);$this->flash->add('success','Next action scheduled.');}catch(\DomainException|\InvalidArgumentException|StaleRecordVersion $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('prospects.show',['id'=>$prospectId]));}
 public function reschedule(Request $q,int $id):Response{$u=$this->auth->user();if(!$u)return Response::redirect($this->router->url('login.form'),302);if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);$row=$this->db->pdo()->prepare('SELECT prospect_id FROM follow_ups WHERE id=:id');$row->execute(['id'=>$id]);$prospectId=(int)$row->fetchColumn();try{$this->service->reschedule($id,(string)($q->body['action']??''),$this->due($q),(int)($q->body['version']??0),(int)($q->body['prospect_version']??0),(int)$u['id'],$q->requestId);$this->flash->add('success','Next action rescheduled.');}catch(\DomainException|\InvalidArgumentException|StaleRecordVersion $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('prospects.show',['id'=>$prospectId]));}
 public function close(Request $q,int $id,bool $cancel):Response{$u=$this->auth->user();if(!$u)return Response::redirect($this->router->url('login.form'),302);if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);$row=$this->db->pdo()->prepare('SELECT prospect_id FROM follow_ups WHERE id=:id');$row->execute(['id'=>$id]);$prospectId=(int)$row->fetchColumn();try{$this->service->close($id,(int)($q->body['version']??0),$cancel,(string)($q->body['reason']??''),(int)$u['id'],$q->requestId);$this->flash->add('success',$cancel?'Follow-up cancelled.':'Follow-up completed.');}catch(\DomainException|\InvalidArgumentException|StaleRecordVersion $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('prospects.show',['id'=>$prospectId]));}
 public function work():Response{$u=$this->auth->user();if(!$u)return Response::redirect($this->router->url('login.form'),302);$tz=new DateTimeZone((string)$this->db->pdo()->query('SELECT owner_timezone FROM application_settings WHERE id=1')->fetchColumn());$now=$this->clock->now();$today=$now->setTimezone($tz)->setTime(0,0);$end=$today->modify('+8 days')->setTimezone(new DateTimeZone('UTC'));$s=$this->db->pdo()->prepare("SELECT f.*,p.version prospect_version,p.segment,p.status,c.name company_name,CONCAT_WS(' ',ct.first_name,ct.last_name) contact_name,p.last_contact_at FROM follow_ups f JOIN prospects p ON p.id=f.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id WHERE f.status='open' AND p.archived_at IS NULL AND f.due_at < :end ORDER BY f.due_at,f.id");$s->execute(['end'=>$end->format('Y-m-d H:i:s.u')]);$queues=['overdue'=>[],'today'=>[],'upcoming'=>[]];$classifier=new DueClassifier($tz);foreach($s->fetchAll() as $row){$class=$classifier->classify(new DateTimeImmutable($row['due_at'],new DateTimeZone('UTC')),$now);$queues[$class][]=$row;}return $this->shell->owner('work/index.php',['queues'=>$queues,'csrfToken'=>$this->csrf->token(),'completeUrl'=>fn(int $id)=>$this->router->url('followups.complete',['id'=>$id]),'cancelUrl'=>fn(int $id)=>$this->router->url('followups.cancel',['id'=>$id]),'rescheduleUrl'=>fn(int $id)=>$this->router->url('followups.reschedule',['id'=>$id])],$u,'Daily work','work.index');}
 public function history(Request $q):Response{$u=$this->auth->user();if(!$u)return Response::redirect($this->router->url('login.form'),302);$list=\Dreamsmith\Campaign\Reporting\ListQuery::from($q->query,['due','status','updated'],'due');$status=is_string($q->query['status']??null)?$q->query['status']:'';if(!in_array($status,['','open','completed','cancelled'],true))$status='';$repository=new FollowUpRepository($this->db->pdo());$count=$repository->count($status,$list->text);return $this->shell->owner('follow-ups/history.php',['followUps'=>$repository->history($status,$list->text,$list->sort,$list->direction,$list->size,$list->offset()),'filters'=>['q'=>$list->text,'sort'=>$list->sort,'direction'=>$list->direction,'status'=>$status],'count'=>$count,'page'=>$list->page,'pages'=>max(1,(int)ceil($count/$list->size)),'indexUrl'=>$this->router->url('followups.index'),'prospectUrl'=>fn(int $id):string=>$this->router->url('prospects.show',['id'=>$id])],$u,'Follow-up history','followups.index');}
 private function due(Request $q):DateTimeImmutable{$tz=new DateTimeZone((string)$this->db->pdo()->query('SELECT owner_timezone FROM application_settings WHERE id=1')->fetchColumn());$due=DateTimeImmutable::createFromFormat('!Y-m-d\TH:i',(string)($q->body['due_at']??''),$tz);if($due===false)throw new \InvalidArgumentException('Enter a valid due time.');return $due->setTimezone(new DateTimeZone('UTC'));}
}
