<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\FollowUp;
use DateTimeImmutable;use Dreamsmith\Campaign\Application\Audit\ActorContext;use Dreamsmith\Campaign\Application\Audit\AuditWriter;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Support\Clock;use PDO;
final class FollowUpService{
 public function __construct(private readonly Database $db,private readonly AuditWriter $audit,private readonly Clock $clock){}
 public function schedule(int $prospectId,string $action,DateTimeImmutable $due,int $prospectVersion,int $owner,string $cid):int{$action=$this->action($action);return $this->db->transaction(function(PDO $p)use($prospectId,$action,$due,$prospectVersion,$owner,$cid){$this->lockedProspect($p,$prospectId,$prospectVersion);$q=$p->prepare("SELECT id FROM follow_ups WHERE prospect_id=:id AND status='open' FOR UPDATE");$q->execute(['id'=>$prospectId]);if($q->fetch())throw new \DomainException('This prospect already has a next action. Reschedule it instead.');$p->prepare("INSERT INTO follow_ups(prospect_id,action,due_at,actor_user_id) VALUES(:prospect,:action,:due,:owner)")->execute(['prospect'=>$prospectId,'action'=>$action,'due'=>$due->format('Y-m-d H:i:s.u'),'owner'=>$owner]);$id=(int)$p->lastInsertId();$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'follow_up.created','follow_up',$id,[],$this->clock->now());return$id;});}
 public function reschedule(int $id,string $action,DateTimeImmutable $due,int $version,int $prospectVersion,int $owner,string $cid):void{$action=$this->action($action);$this->db->transaction(function(PDO $p)use($id,$action,$due,$version,$prospectVersion,$owner,$cid){$q=$p->prepare('SELECT * FROM follow_ups WHERE id=:id FOR UPDATE');$q->execute(['id'=>$id]);$f=$q->fetch();if(!$f||$f['status']!=='open')throw new \DomainException('Follow-up is no longer open.');if((int)$f['version']!==$version)throw new StaleRecordVersion('Follow-up changed.');$this->lockedProspect($p,(int)$f['prospect_id'],$prospectVersion);$p->prepare('UPDATE follow_ups SET action=:action,due_at=:due,version=version+1 WHERE id=:id')->execute(['action'=>$action,'due'=>$due->format('Y-m-d H:i:s.u'),'id'=>$id]);$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'follow_up.rescheduled','follow_up',$id,[],$this->clock->now());});}
 public function close(int $id,int $version,bool $cancel,string $reason,int $owner,string $cid):void{$this->db->transaction(function(PDO $p)use($id,$version,$cancel,$reason,$owner,$cid){$q=$p->prepare('SELECT * FROM follow_ups WHERE id=:id FOR UPDATE');$q->execute(['id'=>$id]);$f=$q->fetch();if(!$f||$f['status']!=='open')throw new \DomainException('Follow-up is no longer open.');if((int)$f['version']!==$version)throw new StaleRecordVersion('Follow-up changed.');if($cancel&&trim($reason)==='')throw new \InvalidArgumentException('A cancellation reason is required.');$p->prepare('UPDATE follow_ups SET status=:status,completed_at=:completed,cancelled_at=:cancelled,cancellation_reason=:reason,version=version+1 WHERE id=:id')->execute(['status'=>$cancel?'cancelled':'completed','completed'=>$cancel?null:$this->clock->now()->format('Y-m-d H:i:s.u'),'cancelled'=>$cancel?$this->clock->now()->format('Y-m-d H:i:s.u'):null,'reason'=>$cancel?trim($reason):null,'id'=>$id]);$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),$cancel?'follow_up.cancelled':'follow_up.completed','follow_up',$id,[],$this->clock->now());});}
 private function action(string $action):string{$action=trim($action);if($action==='')throw new \InvalidArgumentException('Next action is required.');return $action;}
 private function lockedProspect(PDO $p,int $id,int $version):void{$q=$p->prepare('SELECT version,archived_at FROM prospects WHERE id=:id FOR UPDATE');$q->execute(['id'=>$id]);$prospect=$q->fetch();if(!$prospect||$prospect['archived_at']!==null)throw new \DomainException('Select an active prospect.');if((int)$prospect['version']!==$version)throw new StaleRecordVersion('Prospect changed.');}
}
