<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Opportunity;
use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\Http\Request;use Dreamsmith\Campaign\Http\Response;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Presentation\ShellRenderer;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Security\Csrf;
final class OpportunityController{
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $db,private readonly OpportunityService $service,private readonly array $sales,private readonly ShellRenderer $shell,private readonly FlashBag $flash,private readonly Csrf $csrf,private readonly Router $router){}
 public function index(Request $q):Response{$u=$this->user();if($u instanceof Response)return $u;$list=\Dreamsmith\Campaign\Reporting\ListQuery::from($q->query);$stage=(string)($q->query['stage']??'');$offer=(string)($q->query['offer']??'');if(!isset($this->sales['opportunity_stages'][$stage]))$stage='';if(!isset($this->sales['opportunity_offers'][$offer]))$offer='';$r=new OpportunityRepository($this->db->pdo());$count=$r->count($list->text,$stage,$offer);return $this->shell->owner('opportunities/index.php',['opportunities'=>$r->all($list->text,$stage,$offer,$list->size,$list->offset()),'stages'=>$this->sales['opportunity_stages'],'offers'=>$this->sales['opportunity_offers'],'filters'=>['q'=>$list->text,'stage'=>$stage,'offer'=>$offer],'count'=>$count,'page'=>$list->page,'pages'=>max(1,(int)ceil($count/$list->size)),'indexUrl'=>$this->router->url('opportunities.index'),'showUrl'=>fn(int $id)=>$this->router->url('opportunities.show',['id'=>$id])],$u,'Opportunities','opportunities.index');}
 public function create(Request $q,int $prospect):Response{return $this->mutation($q,function(array $u)use($q,$prospect){return $this->service->create($prospect,$q->body,(int)($q->body['prospect_version']??0),(int)$u['id'],$q->requestId);},fn(int $id)=>$this->router->url('opportunities.show',['id'=>$id]),'Opportunity created.');}
 public function show(int $id):Response{$u=$this->user();if($u instanceof Response)return $u;$r=new OpportunityRepository($this->db->pdo());$o=$r->find($id);if(!$o)return Response::html('Opportunity not found.',404);return $this->shell->owner('opportunities/show.php',['opportunity'=>$o,'events'=>$r->events($id),'stages'=>$this->sales['opportunity_stages'],'offers'=>$this->sales['opportunity_offers'],'allowed'=>$this->sales['opportunity_transitions'][$o['stage']]??[],'csrfToken'=>$this->csrf->token(),'editUrl'=>$this->router->url('opportunities.edit',['id'=>$id]),'updateUrl'=>$this->router->url('opportunities.update',['id'=>$id]),'transitionUrl'=>$this->router->url('opportunities.transition',['id'=>$id])],$u,'Opportunity','opportunities.index');}
 public function edit(int $id):Response{return $this->show($id);}
 public function update(Request $q,int $id):Response{return $this->mutation($q,function(array $u)use($q,$id){$this->service->update($id,$q->body,(int)($q->body['version']??0),(int)$u['id'],$q->requestId);return $id;},fn(int $id)=>$this->router->url('opportunities.show',['id'=>$id]),'Opportunity updated.');}
 public function transition(Request $q,int $id):Response{return $this->mutation($q,function(array $u)use($q,$id){$this->service->transition($id,(string)($q->body['to_stage']??''),(string)($q->body['reason']??''),(int)($q->body['version']??0),(string)($q->body['follow_up_disposition']??''),(int)$u['id'],$q->requestId);return $id;},fn(int $id)=>$this->router->url('opportunities.show',['id'=>$id]),'Opportunity stage updated.');}
 public function voidEvent(Request $q,int $id,int $eventId):Response{return $this->mutation($q,function(array $u)use($q,$id,$eventId){$this->service->voidLatestEvent($id,$eventId,(int)($q->body['version']??0),(int)($q->body['event_version']??0),(string)($q->body['void_reason']??''),(int)$u['id'],$q->requestId);return $id;},fn(int $id)=>$this->router->url('opportunities.show',['id'=>$id]),'Latest stage event voided.');}
 private function mutation(Request $q,callable $op,callable $url,string $message):Response{$u=$this->user();if($u instanceof Response)return $u;if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);try{$id=$op($u);$this->flash->add('success',$message);}catch(\DomainException|\InvalidArgumentException|\OutOfBoundsException|StaleRecordVersion $e){$this->flash->add('error',$e->getMessage());$id=(int)($q->body['opportunity_id']??0);}return Response::redirect($url($id));}
 private function user():array|Response{return $this->auth->user()??Response::redirect($this->router->url('login.form'),302);}
}
