<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Opportunity;
use Dreamsmith\Campaign\Application\Audit\ActorContext;use Dreamsmith\Campaign\Application\Audit\AuditWriter;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Support\Clock;use PDO;use PDOException;
final class OpportunityService{
 public function __construct(private readonly Database $db,private readonly AuditWriter $audit,private readonly Clock $clock,private readonly array $sales){}
 public function create(int $prospectId,array $v,int $prospectVersion,int $owner,string $cid):int{return $this->db->transaction(function(PDO $p)use($prospectId,$v,$prospectVersion,$owner,$cid){$prospect=$this->prospect($p,$prospectId,$prospectVersion);if($prospect['status']!=='qualified')throw new \DomainException('Only qualified prospects can enter the pipeline.');[$offer,$value,$date]=$this->values($v);try{$p->prepare("INSERT INTO opportunities(prospect_id,offer_key,value_amount,expected_close_on) VALUES(:prospect,:offer,:value,:close)")->execute(['prospect'=>$prospectId,'offer'=>$offer,'value'=>$value,'close'=>$date]);}catch(PDOException $e){if($e->getCode()==='23000')throw new \DomainException('This prospect already has an open opportunity.');throw $e;}$id=(int)$p->lastInsertId();$this->event($p,$id,null,'qualified',null,$owner);if(($v['attach_follow_up']??'')==='1')$p->prepare("UPDATE follow_ups SET opportunity_id=:opportunity,version=version+1 WHERE prospect_id=:prospect AND status='open'")->execute(['opportunity'=>$id,'prospect'=>$prospectId]);$this->audit($p,$owner,$cid,'opportunity.created',$id);return $id;});}
 public function update(int $id,array $v,int $version,int $owner,string $cid):void{$this->db->transaction(function(PDO $p)use($id,$v,$version,$owner,$cid){$o=(new OpportunityRepository($p))->find($id,true);$this->current($o,$version);if(in_array($o['stage'],['won','lost'],true))throw new \DomainException('Closed opportunities cannot be edited.');[$offer,$value,$date]=$this->values($v);$p->prepare('UPDATE opportunities SET offer_key=:offer,value_amount=:value,expected_close_on=:close,version=version+1 WHERE id=:id')->execute(['offer'=>$offer,'value'=>$value,'close'=>$date,'id'=>$id]);$this->audit($p,$owner,$cid,'opportunity.updated',$id);});}
 public function transition(int $id,string $to,string $reason,int $version,string $disposition,int $owner,string $cid):void{$this->db->transaction(function(PDO $p)use($id,$to,$reason,$version,$disposition,$owner,$cid){$o=(new OpportunityRepository($p))->find($id,true);$this->current($o,$version);if(!in_array($to,$this->sales['opportunity_transitions'][$o['stage']]??[],true))throw new \DomainException('That stage change is not allowed.');$reason=trim($reason);if($to==='lost'&&$reason==='')throw new \InvalidArgumentException('A loss reason is required.');$terminal=in_array($to,['won','lost'],true);if($terminal)$this->disposeFollowUp($p,$id,$disposition,$reason);$p->prepare('UPDATE opportunities SET stage=:stage,closed_at=:closed,lost_reason=:reason,version=version+1 WHERE id=:id')->execute(['stage'=>$to,'closed'=>$terminal?$this->at():null,'reason'=>$to==='lost'?$reason:null,'id'=>$id]);$this->event($p,$id,$o['stage'],$to,$reason?:null,$owner);$this->audit($p,$owner,$cid,'opportunity.transitioned',$id);});}
 public function voidLatestEvent(int $id,int $eventId,int $opportunityVersion,int $eventVersion,string $reason,int $owner,string $cid):void{$reason=trim($reason);if($reason==='')throw new \InvalidArgumentException('A correction reason is required.');$this->db->transaction(function(PDO $p)use($id,$eventId,$opportunityVersion,$eventVersion,$reason,$owner,$cid){$o=(new OpportunityRepository($p))->find($id,true);$this->current($o,$opportunityVersion);$s=$p->prepare('SELECT * FROM opportunity_stage_events WHERE opportunity_id=:id AND voided_at IS NULL ORDER BY occurred_at DESC,id DESC LIMIT 1 FOR UPDATE');$s->execute(['id'=>$id]);$event=$s->fetch();if(!$event||(int)$event['id']!==$eventId||$event['from_stage']===null)throw new \DomainException('Only the latest non-initial stage event can be voided.');if((int)$event['version']!==$eventVersion)throw new StaleRecordVersion('Stage event changed.');$p->prepare('UPDATE opportunity_stage_events SET voided_at=:at,voided_reason=:reason,voided_by_user_id=:owner,version=version+1 WHERE id=:id')->execute(['at'=>$this->at(),'reason'=>$reason,'owner'=>$owner,'id'=>$eventId]);$s=$p->prepare('SELECT to_stage FROM opportunity_stage_events WHERE opportunity_id=:id AND voided_at IS NULL ORDER BY occurred_at DESC,id DESC LIMIT 1');$s->execute(['id'=>$id]);$stage=(string)$s->fetchColumn();$p->prepare('UPDATE opportunities SET stage=:stage,closed_at=NULL,lost_reason=NULL,version=version+1 WHERE id=:id')->execute(['stage'=>$stage,'id'=>$id]);$this->audit($p,$owner,$cid,'opportunity.stage_event_voided',$id);});}
 private function disposeFollowUp(PDO $p,int $id,string $how,string $reason):void{$s=$p->prepare("SELECT id FROM follow_ups WHERE opportunity_id=:id AND status='open' FOR UPDATE");$s->execute(['id'=>$id]);$f=$s->fetchColumn();if(!$f)return;if(!in_array($how,['complete','cancel','retain'],true))throw new \DomainException('Choose how to handle the open next action before closing.');if($how==='retain'){$p->prepare('UPDATE follow_ups SET opportunity_id=NULL,version=version+1 WHERE id=:id')->execute(['id'=>$f]);return;}$p->prepare('UPDATE follow_ups SET status=:status,completed_at=:completed,cancelled_at=:cancelled,cancellation_reason=:reason,version=version+1 WHERE id=:id')->execute(['status'=>$how==='complete'?'completed':'cancelled','completed'=>$how==='complete'?$this->at():null,'cancelled'=>$how==='cancel'?$this->at():null,'reason'=>$how==='cancel'?($reason?:'Opportunity closed'):null,'id'=>$f]);}
 private function prospect(PDO $p,int $id,int $version):array{$s=$p->prepare('SELECT * FROM prospects WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r||(int)$r['version']!==$version)throw new StaleRecordVersion('Prospect changed.');return $r;}
 private function values(array $v):array{$offer=(string)($v['offer_key']??'');if(!isset($this->sales['opportunity_offers'][$offer]))throw new \InvalidArgumentException('Select an offer.');$value=(string)($v['value_amount']??'');if(!preg_match('/^\d+(\.\d{1,2})?$/',$value))throw new \InvalidArgumentException('Value must be a nonnegative amount with at most two decimal places.');$date=(string)($v['expected_close_on']??'');if($date!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date))throw new \InvalidArgumentException('Expected close date is invalid.');return[$offer,$value,$date?:null];}
 private function current(?array $o,int $version):void{if(!$o)throw new \OutOfBoundsException('Opportunity not found.');if((int)$o['version']!==$version)throw new StaleRecordVersion('Opportunity changed.');}
 private function event(PDO $p,int $id,?string $from,string $to,?string $reason,int $owner):void{$p->prepare('INSERT INTO opportunity_stage_events(opportunity_id,from_stage,to_stage,occurred_at,reason,actor_user_id) VALUES(:id,:from,:to,:at,:reason,:owner)')->execute(['id'=>$id,'from'=>$from,'to'=>$to,'at'=>$this->at(),'reason'=>$reason,'owner'=>$owner]);}
 private function at():string{return $this->clock->now()->format('Y-m-d H:i:s.u');}private function audit(PDO $p,int $owner,string $cid,string $op,int $id):void{$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),$op,'opportunity',$id,[],$this->clock->now());}
}
