<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Opportunity;
use PDO;
final class OpportunityRepository{
 public function __construct(private readonly PDO $pdo){}
 public function all(string $text='',string $stage='',string $offer='',int $limit=25,int $offset=0):array{$where=[];$params=[];if($text!==''){$where[]="(c.name LIKE :q OR CONCAT_WS(' ',ct.first_name,ct.last_name) LIKE :q OR o.offer_key LIKE :q OR o.lost_reason LIKE :q)";$params['q']='%'.$text.'%';}if($stage!==''){$where[]='o.stage=:stage';$params['stage']=$stage;}if($offer!==''){$where[]='o.offer_key=:offer';$params['offer']=$offer;}$sql="SELECT o.*,c.name company_name,CONCAT_WS(' ',ct.first_name,ct.last_name) contact_name,f.action follow_up_action,f.due_at follow_up_due FROM opportunities o JOIN prospects p ON p.id=o.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id LEFT JOIN follow_ups f ON f.opportunity_id=o.id AND f.status='open'".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY o.updated_at DESC,o.id DESC LIMIT :limit OFFSET :offset";$s=$this->pdo->prepare($sql);foreach($params as $k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':limit',$limit,PDO::PARAM_INT);$s->bindValue(':offset',$offset,PDO::PARAM_INT);$s->execute();return $s->fetchAll();}
 public function count(string $text='',string $stage='',string $offer=''):int{$where=[];$params=[];if($text!==''){$where[]="(c.name LIKE :q OR CONCAT_WS(' ',ct.first_name,ct.last_name) LIKE :q OR o.offer_key LIKE :q OR o.lost_reason LIKE :q)";$params['q']='%'.$text.'%';}if($stage!==''){$where[]='o.stage=:stage';$params['stage']=$stage;}if($offer!==''){$where[]='o.offer_key=:offer';$params['offer']=$offer;}$s=$this->pdo->prepare("SELECT COUNT(*) FROM opportunities o JOIN prospects p ON p.id=o.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id".($where?' WHERE '.implode(' AND ',$where):''));$s->execute($params);return(int)$s->fetchColumn();}
 public function find(int $id,bool $lock=false):?array{$s=$this->pdo->prepare("SELECT o.*,p.status prospect_status,p.qualification_notes,c.name company_name,CONCAT_WS(' ',ct.first_name,ct.last_name) contact_name FROM opportunities o JOIN prospects p ON p.id=o.prospect_id LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id WHERE o.id=:id".($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
 public function events(int $id):array{$s=$this->pdo->prepare('SELECT * FROM opportunity_stage_events WHERE opportunity_id=:id ORDER BY occurred_at DESC,id DESC');$s->execute(['id'=>$id]);return $s->fetchAll();}
}
