<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Prospect;
use Dreamsmith\Campaign\Interaction\InteractionRepository;
use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\Http\Request;use Dreamsmith\Campaign\Http\Response;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Presentation\ShellRenderer;use Dreamsmith\Campaign\Records\RecordRepository;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Security\Csrf;
final class ProspectController{
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $db,private readonly ProspectService $service,private readonly ProspectRules $rules,private readonly array $sales,private readonly ShellRenderer $shell,private readonly FlashBag $flash,private readonly Csrf $csrf,private readonly Router $router){}
 public function index(Request $q):Response{$u=$this->user();if($u instanceof Response)return $u;$campaign=$this->db->pdo()->query('SELECT active_campaign_id FROM application_settings WHERE id=1')->fetchColumn();if(!$campaign){$this->flash->add('info','Activate a campaign before adding or viewing prospects.');return Response::redirect($this->router->url('campaign.settings'),302);}$archived=($q->query['archived']??null)==='1';$list=\Dreamsmith\Campaign\Reporting\ListQuery::from($q->query,['updated','name','status']);$segment=(string)($q->query['segment']??'');$status=(string)($q->query['status']??'');if(!isset($this->sales['segments'][$segment]))$segment='';if(!isset($this->sales['statuses'][$status]))$status='';$repo=new ProspectRepository($this->db->pdo());$count=$repo->count((int)$campaign,$archived,$list->text,$segment,$status);$filters=['q'=>$list->text,'segment'=>$segment,'status'=>$status,'sort'=>$list->sort,'direction'=>$list->direction,'archived'=>$archived?'1':''];return $this->shell->owner('prospects/index.php',['prospects'=>$repo->all((int)$campaign,$archived,$list->text,$segment,$status,$list->sort,$list->direction,$list->size,$list->offset()),'archived'=>$archived,'filters'=>$filters,'count'=>$count,'page'=>$list->page,'pages'=>max(1,(int)ceil($count/$list->size)),'newUrl'=>$this->router->url('prospects.new'),'showUrl'=>fn(int $id)=>$this->router->url('prospects.show',['id'=>$id]),'indexUrl'=>$this->router->url('prospects.index'),'activeUrl'=>$this->router->url('prospects.index'),'archivedUrl'=>$this->router->url('prospects.index').'?archived=1','segments'=>$this->sales['segments'],'statuses'=>$this->sales['statuses']],$u,'Prospects','prospects.index');}
 public function form(?int $id=null,array $v=[],array $e=[],int $status=200):Response{$u=$this->user();if($u instanceof Response)return $u;$repo=new ProspectRepository($this->db->pdo());$p=$id? $repo->find($id):null;if($id&& !$p)return Response::html('Prospect not found.',404);$v=$v?:($p??[]);$records=new RecordRepository($this->db->pdo());return $this->shell->owner('prospects/form.php',['prospect'=>$p,'values'=>$v,'errors'=>$e,'companies'=>$records->activeCompanies(),'contacts'=>$records->activeContacts(),'segments'=>$this->sales['segments'],'csrfToken'=>$this->csrf->token(),'actionUrl'=>$id?$this->router->url('prospects.update',['id'=>$id]):$this->router->url('prospects.create'),'cancelUrl'=>$id?$this->router->url('prospects.show',['id'=>$id]):$this->router->url('prospects.index'),'quickCompanyUrl'=>$this->router->url('records.quick-companies'),'quickContactUrl'=>$this->router->url('records.quick-contacts')],$u,$id?'Edit prospect':'New prospect','prospects.index',$status);}
 public function save(Request $q,?int $id=null):Response{$u=$this->user();if($u instanceof Response)return $u;if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);[$i,$e]=ProspectInput::fromArray($q->body,$this->sales);if(!$i)return $this->form($id,$q->body,$e,422);try{if($id)$this->service->update($id,$i,(int)($q->body['version']??0),(int)$u['id'],$q->requestId);else$id=$this->service->create($i,(int)$u['id'],$q->requestId);}catch(\DomainException $x){return $this->form($id,$q->body,['identity'=>$x->getMessage()],422);}catch(StaleRecordVersion $x){return $this->form($id,[],['conflict'=>$x->getMessage()],409);}$this->flash->add('success','Prospect saved.');return Response::redirect($this->router->url('prospects.show',['id'=>$id]));}
 public function show(int $id):Response{$u=$this->user();if($u instanceof Response)return $u;$r=new ProspectRepository($this->db->pdo());$p=$r->find($id);if(!$p)return Response::html('Prospect not found.',404);$allowed=$this->rules->allowedTransitions($p['status']);$f=$this->db->pdo()->prepare("SELECT * FROM follow_ups WHERE prospect_id=:id AND status='open'");$f->execute(['id'=>$id]);$followUp=$f->fetch()?:null;return $this->shell->owner('prospects/show.php',['prospect'=>$p,'signals'=>$r->signals($id),'events'=>$r->events($id),'interactions'=>(new InteractionRepository($this->db->pdo()))->forProspect($id),'followUp'=>$followUp,'signalTypes'=>$r->signalTypes(),'allowed'=>$allowed,'statuses'=>$this->sales['statuses'],'segments'=>$this->sales['segments'],'csrfToken'=>$this->csrf->token(),'editUrl'=>$this->router->url('prospects.edit',['id'=>$id]),'transitionUrl'=>$this->router->url('prospects.transition',['id'=>$id]),'signalUrl'=>$this->router->url('prospects.signals.add',['id'=>$id]),'signalUpdateUrl'=>fn(int $signalId)=>$this->router->url('prospects.signals.update',['id'=>$id,'signalId'=>$signalId]),'signalRemoveUrl'=>fn(int $signalId)=>$this->router->url('prospects.signals.remove',['id'=>$id,'signalId'=>$signalId]),'eventVoidUrl'=>fn(int $eventId)=>$this->router->url('prospects.events.void',['id'=>$id,'eventId'=>$eventId]),'archiveUrl'=>$this->router->url($p['archived_at']?'prospects.restore':'prospects.archive',['id'=>$id]),'interactionUrl'=>$this->router->url('interactions.create',['id'=>$id]),'interactionCorrectUrl'=>fn(int $interactionId)=>$this->router->url('interactions.correct',['id'=>$interactionId]),'interactionTypes'=>$this->sales['interaction_types'],'interactionDirections'=>$this->sales['interaction_directions'],'interactionOutcomes'=>$this->sales['interaction_outcomes'],'followUpUrl'=>$this->router->url('followups.schedule',['id'=>$id]),'followUpRescheduleUrl'=>fn(int $followUpId)=>$this->router->url('followups.reschedule',['id'=>$followUpId])],$u,'Prospect','prospects.index');}
 public function transition(Request $q,int $id):Response{return $this->mutate($q,$id,function($u)use($q,$id){$this->service->transition($id,(string)($q->body['to_status']??''),(string)($q->body['reason']??''),(int)($q->body['version']??0),(int)$u['id'],$q->requestId);},'Status updated.');}
 public function signal(Request $q,int $id):Response{return $this->mutate($q,$id,function($u)use($q,$id){$this->service->addSignal($id,(int)($q->body['signal_id']??0),(string)($q->body['evidence_note']??''),is_string($q->body['observed_on']??null)?$q->body['observed_on']:null,(int)($q->body['version']??0),(int)$u['id'],$q->requestId);},'Signal evidence added.');}
 public function removeSignal(Request $q,int $id,int $signalId):Response{return $this->mutate($q,$id,function($u)use($q,$id,$signalId){$this->service->removeSignal($id,$signalId,(int)($q->body['version']??0),(int)($q->body['signal_version']??0),(int)$u['id'],$q->requestId);},'Signal evidence removed.');}
 public function updateSignal(Request $q,int $id,int $signalId):Response{return $this->mutate($q,$id,function($u)use($q,$id,$signalId){$this->service->updateSignal($id,$signalId,(string)($q->body['evidence_note']??''),is_string($q->body['observed_on']??null)?$q->body['observed_on']:null,(int)($q->body['version']??0),(int)($q->body['signal_version']??0),(int)$u['id'],$q->requestId);},'Signal evidence updated.');}
 public function voidEvent(Request $q,int $id,int $eventId):Response{return $this->mutate($q,$id,function($u)use($q,$id,$eventId){$this->service->voidLatestEvent($id,$eventId,(int)($q->body['version']??0),(int)($q->body['event_version']??0),(string)($q->body['void_reason']??''),(int)$u['id'],$q->requestId);},'Latest status event voided and status recalculated.');}
 public function archive(Request $q,int $id,bool $restore):Response{return $this->mutate($q,$id,function($u)use($q,$id,$restore){$this->service->archive($id,(int)($q->body['version']??0),$restore,(int)$u['id'],$q->requestId);},$restore?'Prospect restored.':'Prospect archived.');}
 private function mutate(Request $q,int $id,callable $op,string $ok):Response{$u=$this->user();if($u instanceof Response)return $u;if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);try{$op($u);$this->flash->add('success',$ok);}catch(\DomainException|\InvalidArgumentException|\OutOfBoundsException|StaleRecordVersion $x){$this->flash->add('error',$x->getMessage());}return Response::redirect($this->router->url('prospects.show',['id'=>$id]));}
 private function user():array|Response{return $this->auth->user()??Response::redirect($this->router->url('login.form').'?return=dashboard',302);}
}
