<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Prospect;
use PDO;
final class ProspectRepository{
 public function __construct(private readonly PDO $pdo){}
 /** @return list<array<string,mixed>> */ public function all(int $campaignId,bool $archived=false,string $text='',string $segment='',string $status='',string $sort='updated',string $direction='desc',int $limit=25,int $offset=0):array{[$where,$params]=$this->filters($campaignId,$archived,$text,$segment,$status);$s=$this->pdo->prepare("SELECT p.*,c.name company_name,ct.first_name,ct.last_name FROM prospects p LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id WHERE ".implode(' AND ',$where).' ORDER BY '.$this->order($sort,$direction).' LIMIT :limit OFFSET :offset');foreach($params as $key=>$value)$s->bindValue(':'.$key,$value);$s->bindValue(':limit',$limit,PDO::PARAM_INT);$s->bindValue(':offset',$offset,PDO::PARAM_INT);$s->execute();return $s->fetchAll();}
 public function count(int $campaignId,bool $archived=false,string $text='',string $segment='',string $status=''):int{[$where,$params]=$this->filters($campaignId,$archived,$text,$segment,$status);$s=$this->pdo->prepare('SELECT COUNT(*) FROM prospects p LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id WHERE '.implode(' AND ',$where));$s->execute($params);return(int)$s->fetchColumn();}
 /** @return array<string,mixed>|null */ public function find(int $id,bool $lock=false):?array{$s=$this->pdo->prepare('SELECT p.*,c.name company_name,ct.first_name,ct.last_name,ct.company_id contact_company_id FROM prospects p LEFT JOIN companies c ON c.id=p.company_id LEFT JOIN contacts ct ON ct.id=p.primary_contact_id WHERE p.id=:id'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);$r=$s->fetch();return is_array($r)?$r:null;}
 /** @return list<array<string,mixed>> */ public function signals(int $id,bool $lock=false):array{$s=$this->pdo->prepare('SELECT ps.*,s.signal_key,s.name FROM prospect_signals ps JOIN signals s ON s.id=ps.signal_id WHERE ps.prospect_id=:id ORDER BY ps.observed_on DESC,ps.id DESC'.($lock?' FOR UPDATE':''));$s->execute(['id'=>$id]);return $s->fetchAll();}
 /** @return list<array<string,mixed>> */ public function events(int $id):array{$s=$this->pdo->prepare('SELECT * FROM prospect_status_events WHERE prospect_id=:id ORDER BY occurred_at DESC,id DESC');$s->execute(['id'=>$id]);return $s->fetchAll();}
 /** @return list<array<string,mixed>> */ public function signalTypes():array{return $this->pdo->query('SELECT * FROM signals ORDER BY id')->fetchAll();}
 /** @return array{0:list<string>,1:array<string,string|int>} */ private function filters(int $campaignId,bool $archived,string $text,string $segment,string $status):array{$where=['p.campaign_id=:campaign','p.archived_at IS '.($archived?'NOT NULL':'NULL')];$params=['campaign'=>$campaignId];if($text!==''){$where[]="(c.name LIKE :q OR CONCAT_WS(' ',ct.first_name,ct.last_name) LIKE :q OR p.source LIKE :q OR p.why_them LIKE :q OR p.business_problem LIKE :q OR p.qualification_notes LIKE :q)";$params['q']='%'.$text.'%';}if($segment!==''){$where[]='p.segment=:segment';$params['segment']=$segment;}if($status!==''){$where[]='p.status=:status';$params['status']=$status;}return[$where,$params];}
 private function order(string $sort,string $direction):string{$columns=['updated'=>'p.updated_at','name'=>'COALESCE(c.name,CONCAT_WS(\' \',ct.last_name,ct.first_name))','status'=>'p.status'];$column=$columns[$sort]??$columns['updated'];$dir=$direction==='asc'?'ASC':'DESC';return "{$column} {$dir},p.id {$dir}";}
}
