<header class="page-header"><div><p class="eyebrow">Contact</p><h1><?= $contact===null?'New contact':'Edit contact' ?></h1><p>A contact may belong to one active company or remain independent.</p></div></header>
<?php if(isset($errors['conflict'])):?><section class="conflict-state" role="alert"><h2>This contact changed</h2><p><?= $escape($errors['conflict']) ?></p></section><?php elseif($errors!==[]):?><div class="validation-summary" role="alert" tabindex="-1" data-validation-summary><h2>Please correct the form</h2><ul><?php foreach($errors as $field=>$message):?><li><a href="#<?= $escape($field) ?>"><?= $escape($message) ?></a></li><?php endforeach;?></ul></div><?php endif;?>
<?php if($duplicates!==[]):?><section class="conflict-state" role="alert"><h2>Potential duplicates found</h2><ul><?php foreach($duplicates as $match):?><li><?= $escape($match) ?></li><?php endforeach;?></ul><p>Confirmation keeps this as a separate contact; no records are merged.</p></section><?php endif;?>
<form method="post" action="<?= $escape($actionUrl) ?>"><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><?php if($contact!==null):?><input type="hidden" name="version" value="<?= $escape($contact['version']) ?>"><?php endif;?>
<div class="form-field"><label for="company_id">Company</label><select id="company_id" name="company_id"><option value="">Independent contact</option><?php foreach($companies as $company):?><option value="<?= $escape($company['id']) ?>"<?= (string)($values['company_id']??'')===(string)$company['id']?' selected':'' ?>><?= $escape($company['name']) ?></option><?php endforeach;?></select><?php if(isset($errors['company_id'])):?><span class="field-error"><?= $escape($errors['company_id']) ?></span><?php endif;?></div>
<?php if($archivedCompanyName!==null):?><div class="flash flash--warning" role="status"><strong>Archived company:</strong> this contact is currently attached to <?= $escape($archivedCompanyName) ?>. Select an active company or choose independent, then confirm the reassignment.</div><label class="checkbox-field"><input type="checkbox" name="confirm_archived_reassociation" value="1" required> Confirm reassignment away from the archived company.</label><?php endif;?>
<?php foreach(['first_name'=>'First name','last_name'=>'Last name','role'=>'Role','email'=>'Email','phone'=>'Phone','linkedin_url'=>'LinkedIn URL'] as $field=>$label):?><div class="form-field"><label for="<?= $escape($field) ?>"><?= $escape($label) ?></label><input id="<?= $escape($field) ?>" name="<?= $escape($field) ?>" value="<?= $escape($values[$field]??'') ?>"><?php if(isset($errors[$field])):?><span class="field-error"><?= $escape($errors[$field]) ?></span><?php endif;?></div><?php endforeach;?>
<?php if($duplicates!==[]):?><label class="checkbox-field"><input type="checkbox" name="confirm_duplicate" value="1" required> Save as a separate contact despite these warnings.</label><?php endif;?><div class="form-actions"><button type="submit">Save contact</button><a href="<?= $escape($cancelUrl) ?>">Cancel</a></div></form>
<?php if($contact!==null):?><section class="settings-panel"><h2><?= $contact['archived_at']===null?'Archive contact':'Restore contact' ?></h2><p>Archive preserves history and removes the contact from normal selection.</p><form method="post" action="<?= $escape($contact['archived_at']===null?$archiveUrl:$restoreUrl) ?>"><input type="hidden" name="_csrf" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="version" value="<?= $escape($contact['version']) ?>"><?php if($contact['archived_at']!==null):?><label class="checkbox-field"><input type="checkbox" name="confirm_duplicate" value="1"> Restore even if a potential duplicate exists.</label><?php endif;?><button class="button button--danger" type="submit"><?= $contact['archived_at']===null?'Archive contact':'Restore contact' ?></button></form></section><?php endif;?>
