CREATE TABLE lead_candidates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source VARCHAR(64) NOT NULL,
    source_id VARCHAR(255) NOT NULL,
    search_query VARCHAR(500) NULL,
    name VARCHAR(160) NOT NULL,
    website VARCHAR(2048) NULL,
    address VARCHAR(500) NULL,
    category VARCHAR(160) NULL,
    business_status VARCHAR(80) NULL,
    fit VARCHAR(32) NOT NULL,
    score INT NOT NULL DEFAULT 0,
    evidence_json TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    reviewed_at DATETIME(6) NULL,
    reviewed_by_user_id BIGINT UNSIGNED NULL,
    version INT UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uq_lead_candidate_source (source, source_id),
    INDEX idx_lead_candidate_queue (status, fit, score, created_at),
    CONSTRAINT fk_lead_candidate_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
