<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Interaction;
use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\HttpRequest;use Dreamsmith\Campaign\HttpResponse;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Security\Csrf;use Dreamsmith\Campaign\Support\Clock;
final class InteractionController{
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $db,private readonly InteractionService $service,private readonly array $sales,private readonly Csrf $csrf,private readonly FlashBag $flash,private readonly Router $router,private readonly Clock $clock){}
 public function record(Request $q,int $prospectId):Response{return $this->run($q,$prospectId,function($user,$timezone)use($q,$prospectId){[$input,$errors]=InteractionInput::fromArray($q->body,$this->sales,$timezone,$this->clock->now());if(!$input)throw new \InvalidArgumentException(reset($errors)?:'Invalid interaction.');$this->service->record($prospectId,$input,(int)($q->body['version']??0),(int)$user['id'],$q->requestId);},'Interaction recorded.');}
 public function correct(Request $q,int $id):Response{$interaction=(new InteractionRepository($this->db->pdo()))->find($id);if(!$interaction)return Response::html('Interaction not found.',404);return $this->run($q,(int)$interaction['prospect_id'],function($user,$timezone)use($q,$id,$interaction){[$input,$errors]=InteractionInput::fromArray($q->body,$this->sales,$timezone,$this->clock->now());if(!$input)throw new \InvalidArgumentException(reset($errors)?:'Invalid correction.');$this->service->correct($id,$input,(int)($q->body['interaction_version']??0),(int)($q->body['prospect_version']??0),(string)($q->body['reason']??''),(int)$user['id'],$q->requestId);},'Interaction corrected.');}
 private function run(Request $q,int $prospectId,callable $operation,string $success):Response{$user=$this->auth->user();if(!$user)return Response::redirect($this->router->url('login.form'),302);if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);$timezone=(string)$this->db->pdo()->query('SELECT owner_timezone FROM application_settings WHERE id=1')->fetchColumn();try{$operation($user,$timezone);$this->flash->add('success',$success);}catch(\DomainException|\InvalidArgumentException|\OutOfBoundsException|\Dreamsmith\Campaign\Records\StaleRecordVersion $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('prospects.show',['id'=>$prospectId]));}
}
