<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Interaction;
use Dreamsmith\Campaign\Application\Audit\ActorContext;use Dreamsmith\Campaign\Application\Audit\AuditWriter;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Records\StaleRecordVersion;use Dreamsmith\Campaign\Support\Clock;use PDO;
final class InteractionService{
 public function __construct(private readonly Database $db,private readonly AuditWriter $audit,private readonly Clock $clock){}
 public function record(int $prospectId,InteractionInput $i,int $prospectVersion,int $owner,string $cid,?int $supersedes=null):int{return $this->db->transaction(function(PDO $p)use($prospectId,$i,$prospectVersion,$owner,$cid,$supersedes){$prospect=$this->prospect($p,$prospectId,$prospectVersion);if($prospect['archived_at']!==null)throw new \DomainException('Restore the prospect before recording communication.');$this->contact($p,$prospect,$i->contactId);$s=$p->prepare('INSERT INTO interactions(prospect_id,contact_id,type,direction,occurred_at,summary,outcome,qualifies_as_contact,qualifies_as_response,supersedes_interaction_id,actor_user_id) VALUES(:prospect,:contact,:type,:direction,:occurred,:summary,:outcome,:qualifies_contact,:qualifies_response,:supersedes,:owner)');$s->execute(['prospect'=>$prospectId,'contact'=>$i->contactId,'type'=>$i->type,'direction'=>$i->direction,'occurred'=>$i->occurredAt->format('Y-m-d H:i:s.u'),'summary'=>$i->summary,'outcome'=>$i->outcome,'qualifies_contact'=>$i->qualifiesContact?1:0,'qualifies_response'=>$i->qualifiesResponse?1:0,'supersedes'=>$supersedes,'owner'=>$owner]);$id=(int)$p->lastInsertId();if($prospect['status']==='ready_to_contact'&&$i->direction==='outbound'&&$i->qualifiesContact){$p->prepare("INSERT INTO prospect_status_events(prospect_id,from_status,to_status,occurred_at,reason,actor_user_id,source_interaction_id) VALUES(:id,'ready_to_contact','contacted',:at,'First qualifying outbound interaction',:owner,:interaction)")->execute(['id'=>$prospectId,'at'=>$this->clock->now()->format('Y-m-d H:i:s.u'),'owner'=>$owner,'interaction'=>$id]);$p->prepare("UPDATE prospects SET status='contacted' WHERE id=:id")->execute(['id'=>$prospectId]);}$this->recalc($p,$prospectId);$p->prepare('UPDATE prospects SET version=version+1 WHERE id=:id')->execute(['id'=>$prospectId]);$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'interaction.recorded','interaction',$id,[],$this->clock->now());return$id;});}
 public function correct(int $interactionId,InteractionInput $input,int $interactionVersion,int $prospectVersion,string $reason,int $owner,string $cid):int{$reason=trim($reason);if($reason==='')throw new \InvalidArgumentException('A correction reason is required.');return $this->db->transaction(function(PDO $p)use($interactionId,$input,$interactionVersion,$prospectVersion,$reason,$owner,$cid){$old=(new InteractionRepository($p))->find($interactionId,true);if(!$old||$old['voided_at']!==null)throw new \DomainException('Only a valid interaction may be corrected.');if((int)$old['version']!==$interactionVersion)throw new StaleRecordVersion('Interaction changed.');$prospect=$this->prospect($p,(int)$old['prospect_id'],$prospectVersion);$this->contact($p,$prospect,$input->contactId);$p->prepare('UPDATE interactions SET voided_at=:at,voided_reason=:reason,voided_by_user_id=:owner,version=version+1 WHERE id=:id')->execute(['at'=>$this->clock->now()->format('Y-m-d H:i:s.u'),'reason'=>$reason,'owner'=>$owner,'id'=>$interactionId]);$p->prepare('UPDATE prospect_status_events SET voided_at=:at,voided_reason=:reason,voided_by_user_id=:owner,version=version+1 WHERE source_interaction_id=:id AND voided_at IS NULL')->execute(['at'=>$this->clock->now()->format('Y-m-d H:i:s.u'),'reason'=>'Interaction corrected: '.$reason,'owner'=>$owner,'id'=>$interactionId]);$this->recalculateStatus($p,(int)$old['prospect_id']);$new=$this->insert($p,(int)$old['prospect_id'],$input,$owner,$interactionId);$this->recalc($p,(int)$old['prospect_id']);$p->prepare('UPDATE prospects SET version=version+1 WHERE id=:id')->execute(['id'=>$old['prospect_id']]);$this->audit->write($p,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'interaction.corrected','interaction',$new,['superseded_interaction_id'=>$interactionId],$this->clock->now());return$new;});}
 private function insert(PDO $p,int $prospectId,InteractionInput $i,int $owner,?int $supersedes):int{$s=$p->prepare('INSERT INTO interactions(prospect_id,contact_id,type,direction,occurred_at,summary,outcome,qualifies_as_contact,qualifies_as_response,supersedes_interaction_id,actor_user_id) VALUES(:prospect,:contact,:type,:direction,:occurred,:summary,:outcome,:qc,:qr,:supersedes,:owner)');$s->execute(['prospect'=>$prospectId,'contact'=>$i->contactId,'type'=>$i->type,'direction'=>$i->direction,'occurred'=>$i->occurredAt->format('Y-m-d H:i:s.u'),'summary'=>$i->summary,'outcome'=>$i->outcome,'qc'=>$i->qualifiesContact?1:0,'qr'=>$i->qualifiesResponse?1:0,'supersedes'=>$supersedes,'owner'=>$owner]);return(int)$p->lastInsertId();}
 private function recalculateStatus(PDO $p,int $id):void{$s=$p->prepare('SELECT to_status FROM prospect_status_events WHERE prospect_id=:id AND voided_at IS NULL ORDER BY occurred_at DESC,id DESC LIMIT 1');$s->execute(['id'=>$id]);$status=$s->fetchColumn();if($status)$p->prepare('UPDATE prospects SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$id]);}
 /** @return array<string,mixed> */ private function prospect(PDO $p,int $id,int $version):array{$s=$p->prepare('SELECT * FROM prospects WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r)throw new \OutOfBoundsException('Prospect not found.');if((int)$r['version']!==$version)throw new StaleRecordVersion('Prospect changed.');return$r;}
 private function contact(PDO $p,array $prospect,?int $id):void{if(!$id)return;$s=$p->prepare('SELECT company_id,archived_at FROM contacts WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);$c=$s->fetch();if(!$c||$c['archived_at']!==null)throw new \DomainException('Select an active compatible contact.');if($prospect['company_id']!==null&&(int)$c['company_id']!==(int)$prospect['company_id'])throw new \DomainException('Contact does not belong to the prospect company.');if($prospect['company_id']===null&&(int)$prospect['primary_contact_id']!==$id)throw new \DomainException('Contact does not match this independent prospect.');}
 private function recalc(PDO $p,int $id):void{$s=$p->prepare('SELECT MAX(occurred_at) FROM interactions WHERE prospect_id=:id AND voided_at IS NULL AND qualifies_as_contact=1');$s->execute(['id'=>$id]);$p->prepare('UPDATE prospects SET last_contact_at=:at WHERE id=:id')->execute(['at'=>$s->fetchColumn()?:null,'id'=>$id]);}
}
