<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\LeadFinder;
use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\Http\Request;use Dreamsmith\Campaign\Http\Response;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Presentation\ShellRenderer;use Dreamsmith\Campaign\Security\Csrf;use Dreamsmith\Campaign\Records\RecordService;use Dreamsmith\Campaign\Records\CompanyInput;use Dreamsmith\Campaign\Records\DuplicateWarning;use Dreamsmith\Campaign\Prospect\ProspectService;use Dreamsmith\Campaign\Prospect\ProspectInput;
final class LeadFinderController {
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $db,private readonly RecordService $records,private readonly ProspectService $prospects,private readonly array $sales,private readonly ShellRenderer $shell,private readonly FlashBag $flash,private readonly Csrf $csrf,private readonly Router $router){}
 public function index(Request $request):Response{$user=$this->user();if($user instanceof Response)return $user;$status=in_array($request->query['status']??'', ['pending','approved','rejected'],true)?$request->query['status']:'pending';$rows=(new LeadCandidateRepository($this->db->pdo()))->all($status);foreach($rows as &$row)$row['evidence']=json_decode((string)$row['evidence_json'],true)?:[];unset($row);return $this->shell->owner('lead-finder/index.php',['candidates'=>$rows,'status'=>$status,'segments'=>$this->sales['segments'],'csrfToken'=>$this->csrf->token(),'indexUrl'=>$this->router->url('lead-finder.index'),'reviewUrl'=>fn(int $id)=>$this->router->url('lead-finder.review',['id'=>$id])],$user,'Lead Finder','lead-finder.index');}
 public function review(Request $request,int $id):Response{$user=$this->user();if($user instanceof Response)return $user;if(!$this->csrf->verify($request->body['_csrf']??null))return Response::html('Forbidden',403);$status=(string)($request->body['status']??'');if(!in_array($status,['approved','rejected'],true))return Response::html('Invalid review action.',422);$repository=new LeadCandidateRepository($this->db->pdo());$candidate=$repository->find($id);if($candidate===null||$candidate['status']!=='pending'){$this->flash->add('warning','That lead was already reviewed.');return Response::redirect($this->router->url('lead-finder.index'));}if($status==='rejected'){$repository->review($id,'rejected',(int)$user['id']);$this->flash->add('success','Lead rejected.');return Response::redirect($this->router->url('lead-finder.index'));}[$company,$companyErrors]=CompanyInput::fromArray(['name'=>$candidate['name'],'website'=>$candidate['website'],'location'=>$candidate['address'],'industry'=>$candidate['category'],'notes'=>implode("\n",json_decode((string)$candidate['evidence_json'],true)?:[])]);[$prospect,$prospectErrors]=ProspectInput::fromArray(['company_id'=>'1','segment'=>$request->body['segment']??'','source'=>'Lead Finder: '.$candidate['source'],'why_them'=>implode("\n",json_decode((string)$candidate['evidence_json'],true)?:[])],$this->sales);if($company===null||$prospect===null){$this->flash->add('error',reset($companyErrors)?:reset($prospectErrors)?:'Could not create this prospect.');return Response::redirect($this->router->url('lead-finder.index'));}try{$companyId=$this->records->createCompany($company,false,(int)$user['id'],$request->requestId);$prospectInput=new ProspectInput($companyId,null,$prospect->segment,$prospect->source,$prospect->whyThem,$prospect->businessProblem,$prospect->qualificationNotes,false,false,false,false);$prospectId=$this->prospects->create($prospectInput,(int)$user['id'],$request->requestId);$repository->review($id,'approved',(int)$user['id']);$this->flash->add('success','Lead approved and prospect created.');return Response::redirect($this->router->url('prospects.show',['id'=>$prospectId]));}catch(DuplicateWarning $e){$this->flash->add('error','A matching company already exists. Open Companies to use the existing record instead.');}catch(\DomainException $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('lead-finder.index'));}
 private function user():array|Response{return $this->auth->user()??Response::redirect($this->router->url('login.form').'?return=lead-finder',302);}
}
