<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\LeadFinder;
use Dreamsmith\Campaign\Application\Audit\ActorContext;use Dreamsmith\Campaign\Application\Audit\AuditWriter;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Support\Clock;
final class LeadCandidateService {
 public function __construct(private readonly Database $db,private readonly AuditWriter $audit,private readonly Clock $clock){}
 /** @param array<string,mixed> $v @return array<string,mixed> */ public function propose(array $v,ActorContext $actor):array{return $this->db->transaction(function($pdo)use($v,$actor){$name=trim((string)($v['name']??''));$source=trim((string)($v['source']??''));$sourceId=trim((string)($v['source_id']??''));$fit=(string)($v['fit']??'');if($name===''||$source===''||$sourceId===''||!in_array($fit,['strong_fit','possible_fit','not_fit'],true))throw new \InvalidArgumentException('A source, source ID, name, and valid fit label are required.');$source=substr($source,0,64);$sourceId=substr($sourceId,0,255);$repository=new LeadCandidateRepository($pdo);$existing=$repository->findBySource($source,$sourceId);if($existing!==null)return ['id'=>(int)$existing['id'],'status'=>(string)$existing['status'],'already_exists'=>true];$evidence=$v['evidence']??[];if(!is_array($evidence))throw new \InvalidArgumentException('Evidence must be a list.');$id=$repository->upsert(['source'=>$source,'source_id'=>$sourceId,'query'=>substr(trim((string)($v['search_query']??'')),0,500)?:null,'name'=>substr($name,0,160),'website'=>self::text($v['website']??null,2048),'address'=>self::text($v['address']??null,500),'category'=>self::text($v['category']??null,160),'business_status'=>self::text($v['business_status']??null,80),'fit'=>$fit,'score'=>(int)($v['score']??0),'evidence'=>json_encode(array_values(array_filter($evidence,'is_string')),JSON_THROW_ON_ERROR)]);$this->audit->write($pdo,$actor,'lead_candidate.proposed','lead_candidate',$id,['fit'=>$fit,'score'=>(int)($v['score']??0)],$this->clock->now());return ['id'=>$id,'status'=>'pending','already_exists'=>false];});}
 private static function text(mixed $value,int $max):?string{$value=is_string($value)?trim($value):'';return $value===''?null:substr($value,0,$max);}
}
