<header class="page-header"><div><p class="eyebrow">Today</p><h1>Campaign workspace</h1><p>Signed in as <?= $escape($user['email']) ?>.</p></div></header>
<?php if ($campaign === null): ?>
    <section class="empty-state"><h2>Set up your campaign</h2><p>Your daily work queue will appear here after campaign configuration is complete.</p><p><a class="button" href="<?= $escape($campaignSetupUrl) ?>">Configure campaign</a></p></section>
<?php else: ?>
    <section class="settings-panel"><h2><?= $escape($campaign['name']) ?></h2><p>Active from <?= $escape($campaign['start_date']) ?> through <?= $escape($campaign['end_date']) ?>.<?php if ($report !== null && $report['campaign']['state'] === 'active'): ?> Day <?= $escape($report['campaign']['day_number']) ?>.<?php elseif ($report !== null): ?> Campaign <?= $escape($report['campaign']['state']) ?>.<?php endif; ?></p><p><a href="<?= $escape($campaignSetupUrl) ?>">Review campaign settings</a> · <a href="<?= $escape($reportUrl) ?>">View full campaign report</a></p></section>
<?php endif; ?>
<?php if ($report !== null): ?>
    <?php $primaryRate = $report['rates']['contact_to_conversation']; ?>
    <section><h2>Today’s priorities</h2><p><a class="button" href="<?= $escape($workUrl) ?>">Open daily work</a></p><div class="card-grid"><article><h3>Overdue</h3><p><?= $escape(count($report['queues']['overdue'])) ?></p></article><article><h3>Due today</h3><p><?= $escape(count($report['queues']['today'])) ?></p></article><article><h3>Next seven days</h3><p><?= $escape(count($report['queues']['next_seven'])) ?></p></article><article><h3>Contact → conversation</h3><p><?= $primaryRate['denominator'] === 0 ? 'Unavailable' : $escape(number_format(100 * $primaryRate['numerator'] / $primaryRate['denominator'], 1)) . '%' ?></p></article></div></section>
    <section><h2>Campaign target progress</h2><div class="table-scroll"><table><thead><tr><th>Metric</th><th>Actual</th><th>Target</th></tr></thead><tbody><?php foreach ($report['targets'] as $target): ?><tr><td><?= $escape($target['label']) ?></td><td><?= $escape($target['actual']) ?></td><td><?= $escape($target['target']) ?></td></tr><?php endforeach; ?></tbody></table></div></section>
    <section><h2>Pipeline</h2><dl class="record-details"><div><dt>Open value</dt><dd>$<?= $escape($report['pipeline']['open_value']) ?></dd></div><div><dt>Won value</dt><dd>$<?= $escape($report['pipeline']['won_value']) ?></dd></div></dl></section>
    <section><h2>Ready to contact</h2><?php if ($report['queues']['ready'] === []): ?><p>No prospects are waiting.</p><?php else: ?><ul><?php foreach ($report['queues']['ready'] as $row): ?><li><a href="<?= $escape($prospectUrl((int) $row['id'])) ?>"><?= $escape($row['company_name'] ?: $row['contact_name']) ?></a></li><?php endforeach; ?></ul><?php endif; ?></section>
    <section><h2>Current funnel</h2><?php if ($report['funnel'] === []): ?><p>No active prospects yet.</p><?php else: ?><ul><?php foreach ($report['funnel'] as $row): ?><li><?= $escape(str_replace('_', ' ', $row['status'])) ?>: <?= $escape($row['total']) ?></li><?php endforeach; ?></ul><?php endif; ?></section>
    <section><h2>Recent activity</h2><?php if ($recentActivity === []): ?><p>No activity recorded yet.</p><?php else: ?><ol class="timeline"><?php foreach ($recentActivity as $item): ?><li><strong><?= $escape($item['kind']) ?></strong> — <?= $escape($item['detail']) ?> <time><?= $escape($item['at_time']) ?></time></li><?php endforeach; ?></ol><?php endif; ?></section>
<?php endif; ?>
