<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Integration;
use DateInterval;use DateTimeImmutable;use PDO;use PDOException;
final class Idempotency{
 public static function validKey(string $key):bool{return preg_match('/^[A-Za-z0-9._~-]{16,128}$/',$key)===1;}
 public static function fingerprint(string $capability,array $input,array $versions=[]):string{ksort($input);ksort($versions);return hash('sha256',json_encode(['capability'=>$capability,'input'=>$input,'versions'=>$versions],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES));}
 /** @return array{state:'new'|'replay',record_id:int,replay:array<string,mixed>|null} */ public function claim(PDO $pdo,int $clientId,string $key,string $operation,string $hash,int $hours,DateTimeImmutable $now):array{if(!self::validKey($key))throw new \InvalidArgumentException('Idempotency key is invalid.');try{$s=$pdo->prepare('INSERT INTO idempotency_records(integration_client_id,idempotency_key,operation_key,request_hash,expires_at) VALUES(:client,:key,:operation,:hash,:expires)');$s->execute(['client'=>$clientId,'key'=>$key,'operation'=>$operation,'hash'=>$hash,'expires'=>$now->add(new DateInterval('PT'.$hours.'H'))->format('Y-m-d H:i:s.u')]);return['state'=>'new','record_id'=>(int)$pdo->lastInsertId(),'replay'=>null];}catch(PDOException $e){if($e->getCode()!=='23000')throw $e;$s=$pdo->prepare('SELECT * FROM idempotency_records WHERE integration_client_id=:client AND idempotency_key=:key FOR UPDATE');$s->execute(['client'=>$clientId,'key'=>$key]);$row=$s->fetch();if(!is_array($row)||(string)$row['operation_key']!==$operation||(string)$row['request_hash']!==$hash)throw new \DomainException('Idempotency key conflicts with a different request.');if($row['completed_at']===null)throw new \DomainException('Idempotency request is in progress.');return['state'=>'replay','record_id'=>(int)$row['id'],'replay'=>json_decode((string)$row['replay_json'],true,flags:JSON_THROW_ON_ERROR)];}}
 /** @param array<string,mixed> $replay */ public function complete(PDO $pdo,int $recordId,string $outcome,array $replay,DateTimeImmutable $now):void{$s=$pdo->prepare('UPDATE idempotency_records SET outcome_code=:outcome,replay_json=:replay,completed_at=:completed WHERE id=:id');$s->execute(['outcome'=>$outcome,'replay'=>json_encode($replay,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES),'completed'=>$now->format('Y-m-d H:i:s.u'),'id'=>$recordId]);}
}
