<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Integration;
use Dreamsmith\Campaign\Application\Audit\ActorContext;use Dreamsmith\Campaign\Application\Audit\AuditWriter;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Support\Clock;use PDO;
final class IntegrationService{
 public function __construct(private readonly Database $database,private readonly AuditWriter $audit,private readonly Clock $clock,private readonly array $config){}
 /** @return array{token:string,client_id:int,expires_at:string} */ public function create(int $owner,string $name,array|string $requested,string $cid):array{$name=trim($name);if($name===''||strlen($name)>160)throw new \InvalidArgumentException('Integration name is required and must be 160 characters or fewer.');$scopes=ScopeSet::validated($requested,(array)$this->config['scopes']);if($scopes->all()===[])throw new \InvalidArgumentException('Choose at least one scope.');$token='crm_'.rtrim(strtr(base64_encode(random_bytes(36)),'+/','-_'),'=');$expires=$this->clock->now()->modify('+'.(int)$this->config['token_ttl_days'].' days');return $this->database->transaction(function(PDO $pdo)use($owner,$name,$scopes,$token,$expires,$cid):array{$identifier='local_'.bin2hex(random_bytes(12));$s=$pdo->prepare('INSERT INTO integration_clients(owner_user_id,client_identifier,display_name,environment,maximum_scopes_json) VALUES(:owner,:identifier,:name,:environment,:scopes)');$s->execute(['owner'=>$owner,'identifier'=>$identifier,'name'=>$name,'environment'=>$this->config['environment'],'scopes'=>json_encode($scopes->all(),JSON_THROW_ON_ERROR)]);$client=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO integration_tokens(integration_client_id,token_hash,token_prefix,expires_at) VALUES(:client,:hash,:prefix,:expires)')->execute(['client'=>$client,'hash'=>hash('sha256',$token),'prefix'=>substr($token,0,16),'expires'=>$expires->format('Y-m-d H:i:s.u')]);$this->audit->write($pdo,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'integration.token_created','integration_client',$client,['scope_count'=>count($scopes->all())],$this->clock->now());return['token'=>$token,'client_id'=>$client,'expires_at'=>$expires->format('Y-m-d H:i:s')];});}
 public function revoke(int $client,int $owner,int $version,string $reason,string $cid):void{$reason=trim($reason);if($reason==='')throw new \InvalidArgumentException('A revocation reason is required.');$this->database->transaction(function(PDO $pdo)use($client,$owner,$version,$reason,$cid):void{$current=(new IntegrationRepository($pdo))->client($client,true);if($current===null||(int)$current['owner_user_id']!==$owner)throw new \OutOfBoundsException('Integration not found.');if((int)$current['version']!==$version)throw new \DomainException('Integration changed. Reload and try again.');if($current['revoked_at']!==null)throw new \DomainException('Integration is already revoked.');$now=$this->clock->now()->format('Y-m-d H:i:s.u');$pdo->prepare('UPDATE integration_clients SET revoked_at=:now,revoked_reason=:reason,version=version+1 WHERE id=:id')->execute(['now'=>$now,'reason'=>$reason,'id'=>$client]);$pdo->prepare('UPDATE integration_tokens SET revoked_at=:now WHERE integration_client_id=:id AND revoked_at IS NULL')->execute(['now'=>$now,'id'=>$client]);$this->audit->write($pdo,new ActorContext('owner',ownerUserId:$owner,correlationId:$cid),'integration.revoked','integration_client',$client,[],$this->clock->now());});}
}
