<?php
declare(strict_types=1);
namespace Dreamsmith\Campaign\Integration;
use Dreamsmith\Campaign\Authentication\AuthenticationService;use Dreamsmith\Campaign\Http\Request;use Dreamsmith\Campaign\Http\Response;use Dreamsmith\Campaign\Http\Router;use Dreamsmith\Campaign\Persistence\Database;use Dreamsmith\Campaign\Presentation\FlashBag;use Dreamsmith\Campaign\Presentation\ShellRenderer;use Dreamsmith\Campaign\Security\Csrf;
final class IntegrationController{
 public function __construct(private readonly AuthenticationService $auth,private readonly Database $database,private readonly IntegrationService $service,private readonly array $config,private readonly ShellRenderer $shell,private readonly FlashBag $flash,private readonly Csrf $csrf,private readonly Router $router){}
 public function index():Response{$u=$this->user();if($u instanceof Response)return $u;return $this->shell->owner('integrations/index.php',['integrations'=>(new IntegrationRepository($this->database->pdo()))->activeForOwner((int)$u['id']),'tokenEnabled'=>(bool)$this->config['local_tokens_enabled'],'newUrl'=>$this->router->url('integrations.new'),'revokeUrl'=>fn(int $id)=>$this->router->url('integrations.revoke',['id'=>$id]),'csrfToken'=>$this->csrf->token()],$u,'Integrations','integrations.index');}
 public function form(array $values=[],array $errors=[],int $status=200):Response{$u=$this->user();if($u instanceof Response)return $u;return $this->shell->owner('integrations/form.php',['values'=>$values,'errors'=>$errors,'scopes'=>$this->config['scopes'],'csrfToken'=>$this->csrf->token(),'actionUrl'=>$this->router->url('integrations.create'),'cancelUrl'=>$this->router->url('integrations.index'),'tokenDays'=>$this->config['token_ttl_days']],$u,'New integration token','integrations.index',$status);}
 public function create(Request $q):Response{$u=$this->user();if($u instanceof Response)return $u;if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);try{$issued=$this->service->create((int)$u['id'],(string)($q->body['display_name']??''),is_array($q->body['scopes']??null)?$q->body['scopes']:[],$q->requestId);}catch(\InvalidArgumentException $e){return $this->form($q->body,['form'=>$e->getMessage()],422);}return $this->shell->owner('integrations/token.php',['issued'=>$issued,'indexUrl'=>$this->router->url('integrations.index')],$u,'Save integration token','integrations.index');}
 public function revoke(Request $q,int $id):Response{$u=$this->user();if($u instanceof Response)return $u;if(!$this->csrf->verify($q->body['_csrf']??null))return Response::html('Forbidden',403);try{$this->service->revoke($id,(int)$u['id'],(int)($q->body['version']??0),(string)($q->body['reason']??''),$q->requestId);$this->flash->add('success','Integration revoked.');}catch(\Throwable $e){$this->flash->add('error',$e->getMessage());}return Response::redirect($this->router->url('integrations.index'));}
 private function user():array|Response{return $this->auth->user()??Response::redirect($this->router->url('login.form').'?return=dashboard',302);}
}
